RR: Working ollama server + notebook (TODO: Choose port for ollama)

diff --git a/template/script.sh.erb b/template/script.sh.erb
--- a/template/script.sh.erb
+++ b/template/script.sh.erb
@@ -1,4 +1,7 @@
 #!/usr/bin/env bash
+set -e -o pipefail
+
+#logger -p user.notice -t "ondemand" -- "User: $USER; SubmitHost: $HOSTNAME; JobName: $SLURM_JOB_NAME; Queue: $SLURM_JOB_PARTITION; JobID: $SLURM_JOB_ID"
 
 # Benchmark info
 echo "TIMING - Starting main script at: $(date)"
@@ -6,34 +9,36 @@ echo "TIMING - Starting main script at: $(date)"
 # Set working directory to home directory
 cd "${HOME}"
 
-#
-# Start Jupyter Notebook Server
-#
-
-<%- unless context.version.blank? -%>
-# Purge the module environment to avoid conflicts
+export PYTHONNOUSERSITE=1
 module purge
-export PYTHONPATH=""
-
-# Load the require modules
-module load <%= context.version %>
-
-# List loaded modules
+module load ollama ollama-python
 module list
-<%- end -%>
 
-# Benchmark info
-echo "TIMING - Starting jupyter at: $(date)"
+# Start ollama server
+apptainer instance run --nv "$OLLAMA_SIF" "ollama-server-$SLURM_JOB_ID"
+apptainer instance list --logs
+
+# Caputer logs from instance
+function capture_in_instance_logs {
+  # Argument is expected to be a regex with a capture group (parens)
+  # for the file to find in `apptainer instance list --logs`
+  regex=$1
+  info="$(apptainer instance list --logs)"
+  if [[ $info =~ $regex ]]; then
+    src="${BASH_REMATCH[1]}"
+    if [[ -f $src ]]; then
+      dest="<%= session.staged_root %>/$(basename "$src")"
+      echo "Tailing '$src' to '$dest'"
+      tail -n +1 -F $src > $dest &
+      return
+    fi
+  fi
+  echo "WARNING: Could not find apptainer instance logfile matching '$regex'"
+}
+
+capture_in_instance_logs '(\S+err\b)'
+capture_in_instance_logs '(\S+out\b)'
 
 # Launch the Jupyter Notebook Server
 set -x
-logger -p user.notice -t "ondemand" -- "User: $USER; SubmitHost: $HOSTNAME; JobName: $SLURM_JOB_NAME; Queue: $SLURM_JOB_PARTITION; JobID: $SLURM_JOB_ID"
-<%- if context.version == "anaconda3/2023.03" %>
-jupyter <%= context.jupyter_interface %> --debug --config="${CONFIG_FILE}" <%= context.extra_jupyter_args %> 
-<%- elsif context.version == "tensorflow/2.13" %>
-apptainer exec --nv "$TENSORFLOW_2_13_SIF" jupyter <%= context.jupyter_interface %> --debug --config="${CONFIG_FILE}" <%= context.extra_jupyter_args %>
-<%- elsif context.version == "pytorch/2.1.0" %>
-apptainer exec --nv "$PYTORCH_2_1_0_SIF" jupyter <%= context.jupyter_interface %> --debug --config="${CONFIG_FILE}" <%= context.extra_jupyter_args %>
-<%- elsif context.version == "pillow/10.2.0" %>
-apptainer exec --nv "$PILLOW_10_2_0_SIF" jupyter <%= context.jupyter_interface %> --debug --config="${CONFIG_FILE}" <%= context.extra_jupyter_args %>
-<%- end -%>
+jupyter <%= context.jupyter_interface %> --debug --config="$CONFIG_FILE" 
